- name: Fetch and run Docker image from Docker Hub
  hosts: localhost
  connection: local
  tasks:
    - name: Pull Docker image from Docker Hub
      docker_image:
        name: "gsamrit/calculator:latest"
        source: pull

    - name: Run Docker container
      command: docker run -d --name calculator-container -p 8082:8082 gsamrit/calculator:latest
